#Goal: To build a CI/CD pipeline(just dummy)
name: CICD Demo

on:
  push:

jobs:
#CI
  code:
    runs-on: ubuntu-latest
    steps:
      - name: clone the code
        #run: echo "Code Clone"
        uses: actions/checkout@v7
        
        
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build the code with docker
        uses: docker/setup-buildx-action@v3
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the Application
        run: echo "Test Passed"
  #CD      
  deploy:
    needs: [code,build,test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App on Server
        run: echo "Application Deployed"
